services:
    bot:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
        - .env
        network_mode: host
        restart: unless-stopped
version: "2.4"
