// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export interface Config {
    owners: string[];
    prefix: string;
    color: string;
    lavalink: {
        hosts: {
            rest: string;
            ws: string;
        };
        password: string;
    };
    myriad: string;
    dev: boolean;
}